{% set name = "jupyter-ai" %}
{% set version = "2.28.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai-{{ version }}.tar.gz
  sha256: 4be34772c3bd2b0dd34736843e57ce2f8b7bb271d2ae2b728df6645354074b89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - jupyter_server >=1.6,<3
    - jupyterlab >=4.0,<5
    - aiosqlite >=0.18
    - importlib-metadata >=5.2.0
    - jupyter-ai-magics ==2.28.2
    - dask-core
    - typing-extensions >=4.5.0
    - distributed
    - traitlets >=5.0,<6
    - deepmerge >=2.0,<3
    - faiss-cpu >=1.8.0,<2

test:
  requires:
    - pip
  imports:
    - jupyter_ai

about:
  summary: A generative AI extension for JupyterLab
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JasonWeill
    - dlqqq
    - 3coins
    - andrii-i
